name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create config.js from prompts and secret API key
      run: |
        # Create config.js by combining prompts and API configuration
        cat > config.js << 'EOF'
        // Configuration file for API keys and settings
        // Generated automatically during deployment
        
        const CONFIG = {
            GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}',
            GEMINI_API_URL: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
            
            // Persian system prompts for each consultation action
            SYSTEM_PROMPTS: {
        EOF
        
        # Extract prompts from config.prompts.js and add to config.js
        node -e "
        const fs = require('fs');
        const content = fs.readFileSync('config.prompts.js', 'utf8');
        const promptsMatch = content.match(/const SYSTEM_PROMPTS = \{([\s\S]*?)\};/);
        if (promptsMatch) {
          const prompts = promptsMatch[1].trim();
          console.log(prompts);
        }
        " >> config.js
        
        # Close the config structure
        cat >> config.js << 'EOF'
            }
        };
        EOF
        
        echo "Generated config.js:"
        head -10 config.js
        
    - name: Prepare deployment directory
      run: |
        mkdir -p _site
        # Copy all files except .git and .github
        rsync -av --exclude='.git' --exclude='.github' --exclude='_site' . _site/
        echo "Files in _site directory:"
        ls -la _site/
        echo "Checking config.js in _site:"
        ls -la _site/config.js
        head -3 _site/config.js
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4